name: jdk-17

on:
  push:
    branches: [ master ]
    paths: [ 'jdk-17/**' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./jdk-17
          tags: fabioformosaddg/maven-firefox:jdk-17,fabioformosaddg/maven-firefox:latest
          push: true
